trigger:
  branches:
    include:
      - main

variables:
  imageName: 'aks-sample'

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<your-service-connection-name>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name devopsacr12345
          docker build -t devopsacr12345.azurecr.io/$(imageName):$(Build.BuildId) .
          docker push devopsacr12345.azurecr.io/$(imageName):$(Build.BuildId)

- stage: Deploy
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<your-service-connection-name>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group devops-rg --name devops-aks
          kubectl set image deployment/aks-sample aks-sample=devopsacr12345.azurecr.io/$(imageName):$(Build.BuildId)
